### ISSUE TITLE
Periodic table not displayed

### ISSUE THREAD

**Issue by njss** [innerdoc/periodic-table-creator#1]
Hello,

Both when I run the code in my local machine and when accessing the demo url:
- the periodic table is not displayed
- locally I get these "Bokeh" errors: 
E-1001 (BAD_COLUMN_NAME): Glyph refers to nonexistent column name. This could either be due to a misspelling or typo, or due to an expected column being missing. : key "text_font" value "Helvetica" [renderer: GlyphRenderer(id='1043', ...)]

**Comment by innerdoc** [comment]
Hi, bokey package version is updated and the text_font improved (value(<font>) instead of <font> ).
Issue is now solved
