### ISSUE TITLE
App is currently broken

### ISSUE THREAD

**Issue by blackary** [innerdoc/periodic-table-creator#3]
There seem to be two issues with https://www.innerdoc.com/periodic-table-demo/

1. There's a too-many-redirects error -- would you mind updating the url to https://innerdoc-pe-periodic-table-creatorperiodic-table-creator-l0jet5.streamlitapp.com/?embedded=true

2. There's an issue with the bokeh version, which should be fixed by #2 

Thanks for making this excellent app!

**Comment by innerdoc** [comment]
Hi, thanks, resolved this by changing the URL and updating the version of Bokeh!
